-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUUOSpAOSHGrC6PdU
nAZafbk+wCf0HhqMmNrcicWksD+gCgYIKoZIzj0DAQehRANCAAT3xo8XHqdI6wfA
8bvXPh3ovih4XTZvvZDqA5Z6zHVW7Whj/jLQpDe/QQY9WfaGHxCPrcI0TAj8y0b0
bc18xdZU
-----END PRIVATE KEY-----